name: Trigger docs build

on:
  push:
    paths:
      - 'docs/**/*'
    branches:
      - main
      - 'releases/*'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DOCS_REPO_ACCESS_TOKEN }}
          repository: upfrontjs/docs
          event-type: build-docs
          client-payload: '{"ref": "${{ github.ref }}", "repo": "${{ github.repository }}"}'
